SELECT B.FLAVOR 
FROM 
(
SELECT A.FLAVOR, SUM(A.TOTAL_ORDER) AS TOTAL_ORDER
FROM (
    SELECT *
    FROM FIRST_HALF 
    UNION ALL 
    SELECT *
    FROM JULY) A
GROUP BY A.FLAVOR
ORDER BY TOTAL_ORDER DESC
LIMIT 3
) B