-- 코드를 작성해주세요
SELECT 
YEAR(E1.DIFFERENTIATION_DATE) AS YEAR, 
(SELECT MAX(SIZE_OF_COLONY) 
 FROM ECOLI_DATA E2 
 WHERE YEAR(E2.DIFFERENTIATION_DATE) = YEAR(E1.DIFFERENTIATION_DATE))
 - E1.SIZE_OF_COLONY AS YEAR_DEV, 
E1.ID 
FROM ECOLI_DATA E1
ORDER BY YEAR, YEAR_DEV