WITH FRONTEND_CODE AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
    CHASH_CODE AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
),
    PYTHON_CODE AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
)

SELECT A.GRADE, A.ID, A.EMAIL
FROM (
    SELECT ID, EMAIL,
    CASE 
        WHEN 
            SKILL_CODE & (SELECT CODE FROM FRONTEND_CODE) != 0 AND
            SKILL_CODE & (SELECT CODE FROM PYTHON_CODE) != 0
        THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM CHASH_CODE) != 0 THEN 'B'
        WHEN SKILL_CODE & (SELECT CODE FROM FRONTEND_CODE) != 0 THEN 'C'
    END AS GRADE
    FROM DEVELOPERS ) A
WHERE A.GRADE IS NOT NULL
ORDER BY A.GRADE, A.ID